version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: aura
      POSTGRES_PASSWORD: aura
      POSTGRES_DB: aura
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://aura:aura@db:5432/aura?schema=public
      JWT_SECRET: supersecret
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"
volumes:
  db_data:
